jwt_secret: "change-me"
default_redirection_url: https://analytics.long-cao.dev

server:
  host: 0.0.0.0
  port: 9091

session:
  name: authelia_session
  secret: "change-me"
  cookies:
    - name: authelia_session
      domain: long-cao.dev
      authelia_url: https://auth.long-cao.dev
  expiration: 1h
  inactivity: 30m

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "analytics.long-cao.dev"
      policy: one_factor

identity_providers:
  oidc:
    hmac_secret: "change-me"
    issuer_private_key: |
      -----BEGIN EC PRIVATE KEY-----
      ...
      -----END EC PRIVATE KEY-----
